/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel;

import com.bi.calendar.dlg.ActDates;
import com.bi.calendar.dlg.JPanelDates;
import com.bi.cities.dlg.ActCities;

import com.bi.jsph.model.Etape;
import com.bi.right.customer.bo.Conseil;
import com.bi.right.customer.bo.GUIManager;
import com.bi.right.customer.panel.sub.CitiesJPanel;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.NotifyDescriptor.Confirmation;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class ConseilJPanel extends AbstractPanel {

    private final static CitiesJPanel CITIESPANEL = new CitiesJPanel();

    /**
     * Creates new form ConseilJPanel
     */
    public ConseilJPanel() {
	initComponents();
    }

    public ConseilJPanel(GUIManager rparent) {
	super(rparent);
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        conseil1 = getParentRoot().getConseil();
        instancencours1 = getParentRoot().getInstance();
        jPanel1 = new javax.swing.JPanel();
        jLabelConseil = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSection = new javax.swing.JTextField(this.conseil1.getSection());
        jLabelChambre = new javax.swing.JLabel();
        jTextFieldChambre = new javax.swing.JTextField();
        jTextFieldRefSaisine = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldInstanceopen = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBldgNb1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabelPostalCd1 = new javax.swing.JLabel();
        jTextFieldPostalCd1 = new javax.swing.JTextField();
        jLabelPhneNb1 = new javax.swing.JLabel();
        jTextFieldPhneNb1 = new javax.swing.JTextField();
        jLabelFaxNb2 = new javax.swing.JLabel();
        jCheckBoxInstanceEncours = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFax = new javax.swing.JTextField();
        jTextFieldInstance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabelConseil, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelConseil.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelVille, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelVille.text")); // NOI18N

        jTextFieldVille.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldVille.toolTipText")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${ville}"), jTextFieldVille, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        bindingGroup.addBinding(binding);

        jTextFieldVille.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldVillePropertyChange(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabel3.text")); // NOI18N

        jTextFieldSection.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldSection.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${section}"), jTextFieldSection, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSectionMouseEntered(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelChambre, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelChambre.text")); // NOI18N

        jTextFieldChambre.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldChambre.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${chambre}"), jTextFieldChambre, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldRefSaisine.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldRefSaisine.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, instancencours1, org.jdesktop.beansbinding.ELProperty.create("${refid}"), jTextFieldRefSaisine, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxInstanceEncours, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jTextFieldRefSaisine, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabel4.text")); // NOI18N

        jFormattedTextFieldInstanceopen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldInstanceopen.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jFormattedTextFieldInstanceopen.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, instancencours1, org.jdesktop.beansbinding.ELProperty.create("${startdt}"), jFormattedTextFieldInstanceopen, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldInstanceopen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldInstanceopenMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabel5.text")); // NOI18N

        jTextFieldBldgNb1.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldBldgNb1.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${addrid.adrline1}"), jTextFieldBldgNb1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${addrid.adrline2}"), jTextField5, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${addrid.adrline3}"), jTextField6, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPostalCd1, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelPostalCd1.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${addrid.pstcd}"), jTextFieldPostalCd1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPhneNb1, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelPhneNb1.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${tel.pnumber}"), jTextFieldPhneNb1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelFaxNb2, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabelFaxNb2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxInstanceEncours, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jCheckBoxInstanceEncours.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${instanceOuverte}"), jCheckBoxInstanceEncours, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabel1.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conseil1, org.jdesktop.beansbinding.ELProperty.create("${fax.pnumber}"), jTextFieldFax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldInstance.setToolTipText(org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jTextFieldInstance.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, instancencours1, org.jdesktop.beansbinding.ELProperty.create("${etatcourant.description}"), jTextFieldInstance, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jList1.setModel(new Etape());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jLabel6.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/empty/search.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(ConseilJPanel.class, "ConseilJPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelConseil))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPostalCd1)
                                    .addComponent(jLabelVille))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPostalCd1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPhneNb1)
                                    .addComponent(jLabelFaxNb2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPhneNb1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelChambre)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBldgNb1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSection, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBoxInstanceEncours)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRefSaisine, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldInstanceopen, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInstance)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelConseil)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxInstanceEncours)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldRefSaisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChambre)
                            .addComponent(jTextFieldChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBldgNb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPostalCd1)
                            .addComponent(jTextFieldPostalCd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVille)
                            .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhneNb1)
                            .addComponent(jTextFieldPhneNb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFaxNb2)
                            .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jFormattedTextFieldInstanceopen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

	SwingUtilities.invokeLater(new Runnable() {
	    @Override
	    public void run() {
		jTextFieldInstance.setText(String.valueOf(jList1.getSelectedValue()));
	    }
	});

    }//GEN-LAST:event_jList1ValueChanged

    private void jTextFieldSectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSectionMouseEntered
	if (isWizardMode()) {
	    super.fillEditorText("Pour juger votre affaire il faut une section compétente. "
		    + "\nSi vous être cadre ou assimilé,"
		    + "c'est la section de l'encadrement."
		    + "\n\t-Section de l’encadrement"
		    + "\nRelèvent de cette section les ingénieurs\n"
		    + " ou les salariés qui ont une formation équivalente\n"
		    + " ou qui ont une délégation de commandement"
		    + "\n\t-Section industrie"
		    + "\nRelèvent de cette section les ouvriers et employés de l’industrie\n"
		    + "\n\t-Section Commerce "
		    + "\nRelèvent de cette section les ouvriers et employés du commerce\n"
		    + "\n\t-Activités diverses"
		    + "\nRelèvent de cette section les ouvriers et employés dont les employeurs\n"
		    + " n’exercent pas une activité d’une autre section et les employés de maison,\n"
		    + " concierges et gardiens d’immeubles"
		    + "\n\t-Agriculture \n"
		    + "Relèvent de cette section les ouvriers et employés des professions agricoles");
	} else {
	    super.fillEditorText("Section de l’encadrement, Section industrie, Section Commerce, Activités diverses");
	}
    }//GEN-LAST:event_jTextFieldSectionMouseEntered

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
	super.fillEditorText("Si vous avez ouvert une instance en cours, c'est-à-dire saisi"
		+ "les Prud'Hommes,renseigner le nom de l'affaire.");
    }//GEN-LAST:event_jList1MouseEntered

    private void jFormattedTextFieldInstanceopenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldInstanceopenMouseClicked

	if (evt.getClickCount() == 2) {
	    JPanelDates datePanel = new JPanelDates(jFormattedTextFieldInstanceopen);
	    ActDates actionlistener = new ActDates(datePanel);
	    DialogDescriptor dd = new DialogDescriptor(datePanel,
		    "Choisissez la date", true,
		    new Object[]{ActDates.Annuler, ActDates.Choisir}, ActDates.Choisir, 0, null, actionlistener);
	    Dialog dc = DialogDisplayer.getDefault().createDialog(dd);
	    actionlistener.setDlg(dc);
	    dc.setVisible(true);
	}

    }//GEN-LAST:event_jFormattedTextFieldInstanceopenMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	SwingUtilities.invokeLater(new Runnable() {
	    @Override
	    public void run() {

		ActCities actionlistener = new ActCities(CITIESPANEL);
		DialogDescriptor dd = new DialogDescriptor(CITIESPANEL,
			"Choisissez la ville", true,
			new Object[]{ActCities.Annuler, ActCities.Choisir}, ActCities.Choisir, 0, null, actionlistener);
		Dialog dlg = DialogDisplayer.getDefault().createDialog(dd);
		actionlistener.setDlg(dlg);
		dlg.setVisible(true);
		Conseil cConseil = actionlistener.getConseilSelected();
		if(cConseil != null){
		jTextFieldVille.setText(cConseil.getAddrid().getTwnnm());
		jTextFieldBldgNb1.setText(cConseil.getAddrid().getAdrline1());
		jTextField5.setText(cConseil.getAddrid().getAdrline2());
		jTextField6.setText(cConseil.getAddrid().getAdrline3());
		jTextFieldPostalCd1.setText(cConseil.getAddrid().getPstcd());
		jTextFieldFax.setText(cConseil.getFax().getPnumber());
		jTextFieldPhneNb1.setText(cConseil.getTel().getPnumber());
		}

	    }
	});


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldVillePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldVillePropertyChange
        // TODO add your handling code here:
	if (evt.getPropertyName().equals("text")){
	    conseil1.getAddrid().setTwnnm(this.jTextFieldVille.getText());
	}
    }//GEN-LAST:event_jTextFieldVillePropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.bo.Conseil conseil1;
    private com.bi.right.customer.bo.Instancencours instancencours1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxInstanceEncours;
    private javax.swing.JFormattedTextField jFormattedTextFieldInstanceopen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelChambre;
    private javax.swing.JLabel jLabelConseil;
    private javax.swing.JLabel jLabelFaxNb2;
    private javax.swing.JLabel jLabelPhneNb1;
    private javax.swing.JLabel jLabelPostalCd1;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldBldgNb1;
    private javax.swing.JTextField jTextFieldChambre;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldInstance;
    private javax.swing.JTextField jTextFieldPhneNb1;
    private javax.swing.JTextField jTextFieldPostalCd1;
    private javax.swing.JTextField jTextFieldRefSaisine;
    private javax.swing.JTextField jTextFieldSection;
    private javax.swing.JTextField jTextFieldVille;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public BindingGroup getBindingGroup() {
	return bindingGroup;
    }

    @Override
    public List<Document> getUndoableDocuments() {
	ArrayList<Document> prj = new ArrayList<Document>();
	prj.add(this.jTextFieldChambre.getDocument());
	prj.add(this.jTextField5.getDocument());
	prj.add(this.jTextField6.getDocument());
	prj.add(this.jTextFieldBldgNb1.getDocument());
	prj.add(this.jTextFieldInstance.getDocument());
	prj.add(this.jTextFieldPhneNb1.getDocument());
	prj.add(this.jTextFieldFax.getDocument());
	prj.add(this.jTextFieldPostalCd1.getDocument());
	prj.add(this.jTextFieldRefSaisine.getDocument());
	prj.add(this.jTextFieldSection.getDocument());
	prj.add(this.jTextFieldVille.getDocument());
	prj.add(this.jFormattedTextFieldInstanceopen.getDocument());
	return prj;
    }

    @Override
    public void initJComponents() {
	initComponents();
    }

    @Override
    public boolean isNextPossible() {
	String newSection = getParentRoot().getConseil().getSection();
	String oldSection = jTextFieldSection.getText();
	if (newSection != null && !"".equals(newSection)) {
	    if (newSection.equals(oldSection)) {
	    } else {
		if ((oldSection != null) && (!"".equals(oldSection.trim()))) {
		    Confirmation dd = new NotifyDescriptor.Confirmation("Voulez vous changer la section :" + oldSection + " par la section :" + newSection + " ", "Changement de section", Confirmation.YES_NO_OPTION);
		    Object result = DialogDisplayer.getDefault().notify(dd);
		    if (result == Confirmation.YES_OPTION) {
			jTextFieldSection.setText(newSection);
		    }
		} else {
		    jTextFieldSection.setText(newSection);
		}
	    }
	}


	if (isEmpty(jTextFieldVille, jTextFieldSection,
		jTextFieldBldgNb1, jTextFieldPostalCd1)) {
	    return false;
	}
	if (jCheckBoxInstanceEncours.isSelected()) {
	    return !isEmpty(jFormattedTextFieldInstanceopen, jTextFieldRefSaisine, jTextFieldInstance);
	}
	return true;
    }
}
