/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel;

import com.bi.right.customer.bo.GUIManager;
import com.bi.right.customer.panel.sub.DemAssistJPanel;
import com.bi.right.customer.panel.sub.DemRepreJPanel;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class DemandeurJPanel1 extends AbstractPanel {

   

    /**
     * Creates new form DemandeurJPanel
     */
    public DemandeurJPanel1() {
        initComponents();
    }

    public DemandeurJPanel1(GUIManager root) {
        super(root);
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroupCadre = new javax.swing.ButtonGroup();
        gUIManager1 = getParentRoot();
        jLabelNamePrefix1Code = new javax.swing.JLabel();
        jComboBoxNamePrefix1Code = new javax.swing.JComboBox();
        jTextFieldNm = new javax.swing.JTextField();
        jTextFieldBldgNb = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabelCitizenship = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldPhneNb = new javax.swing.JTextField();
        jLabelPhneNb = new javax.swing.JLabel();
        jLabelPostalCd = new javax.swing.JLabel();
        jTextFieldPostalCd = new javax.swing.JTextField();
        jTextFieldJob = new javax.swing.JTextField();
        jLabelJob = new javax.swing.JLabel();
        jRadioButtonCadre = new javax.swing.JRadioButton();
        jRadioButtonNonCadre = new javax.swing.JRadioButton();
        jFormattedTextFieldBirthDt = new javax.swing.JFormattedTextField();
        jLabelBirth = new javax.swing.JLabel();
        jLabelBirthPl = new javax.swing.JLabel();
        jTextFieldCityOfBirth = new javax.swing.JTextField();
        jLabelNm = new javax.swing.JLabel();
        jLabelPrenomDemandeur = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCitizen = new javax.swing.JTextField();
        jComboBoxProtected = new javax.swing.JComboBox();
        jLabelProtect = new javax.swing.JLabel();
        jCheckBoxRepresente = new javax.swing.JCheckBox();
        jCheckBoxAssist = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNamePrefix1Code, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelNamePrefix1Code.text")); // NOI18N

        jComboBoxNamePrefix1Code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monsieur", "Madame", "Mademoiselle", " " }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.civilite}"), jComboBoxNamePrefix1Code, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.nm}"), jTextFieldNm, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.addr.adrline1}"), jTextFieldBldgNb, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.pnm}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelCitizenship, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelCitizenship.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.addr.adrline3}"), jTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.addr.adrline2}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.tel.pnumber}"), jTextFieldPhneNb, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPhneNb, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelPhneNb.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPostalCd, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelPostalCd.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.addr.pstcd}"), jTextFieldPostalCd, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.pro}"), jTextFieldJob, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelJob, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelJob.text")); // NOI18N

        buttonGroupCadre.add(jRadioButtonCadre);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonCadre, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jRadioButtonCadre.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.cadre}"), jRadioButtonCadre, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        buttonGroupCadre.add(jRadioButtonNonCadre);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonNonCadre, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jRadioButtonNonCadre.text")); // NOI18N
        jRadioButtonNonCadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNonCadreActionPerformed(evt);
            }
        });

        jFormattedTextFieldBirthDt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.birthdt}"), jFormattedTextFieldBirthDt, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelBirth, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelBirth.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelBirthPl, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelBirthPl.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.cityofbirth}"), jTextFieldCityOfBirth, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNm, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelNm.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPrenomDemandeur, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelPrenomDemandeur.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabel1.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.nationalite}"), jTextFieldCitizen, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jComboBoxProtected.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non protégé", "délégué syndical", "representant du personnel", "Femme enceinte L 1225-4", "En congé de maternité L 1225-4", "Père en cas de décès de la mère en postnatal L1225-28", "Accidenté du travail L1226-9", "Journaliste L7112-5", "Témoin ou dénonciateur de discrimination L1132-3", "Témoin ou  dénonciateur de corruption L1161-1", "Témoin ou dénonciateur ou victime de harcèlement L1152-2", " " }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.tp}"), jComboBoxProtected, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelProtect, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabelProtect.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxRepresente, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jCheckBoxRepresente.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.represente}"), jCheckBoxRepresente, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBoxRepresente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRepresenteItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxAssist, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jCheckBoxAssist.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.represente}"), jCheckBoxAssist, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBoxAssist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAssistItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jLabel2.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.personId.addr.twnnm}"), jTextFieldVille, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jButton1.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxRepresente, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(DemandeurJPanel1.class, "DemandeurJPanel1.jButton2.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxAssist, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jButton2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextFieldBldgNb, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPhneNb)
                                    .addComponent(jLabelJob)))
                            .addComponent(jLabelBirth)
                            .addComponent(jLabelCitizenship)
                            .addComponent(jLabelPrenomDemandeur)
                            .addComponent(jLabelNm)
                            .addComponent(jLabelNamePrefix1Code)
                            .addComponent(jLabelProtect)
                            .addComponent(jLabel1)
                            .addComponent(jLabelPostalCd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNm)
                            .addComponent(jTextFieldPhneNb)
                            .addComponent(jTextFieldJob)
                            .addComponent(jTextField1)
                            .addComponent(jTextFieldCitizen)
                            .addComponent(jComboBoxProtected, 0, 0, Short.MAX_VALUE)
                            .addComponent(jComboBoxNamePrefix1Code, 0, 433, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCadre)
                                        .addGap(37, 37, 37)
                                        .addComponent(jRadioButtonNonCadre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxRepresente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBoxAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldBirthDt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelBirthPl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCityOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 141, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPostalCd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldVille)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelProtect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNamePrefix1Code)
                            .addComponent(jComboBoxNamePrefix1Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrenomDemandeur))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCitizenship)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhneNb)
                            .addComponent(jTextFieldPhneNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJob)
                            .addComponent(jTextFieldJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBirth)
                            .addComponent(jFormattedTextFieldBirthDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBirthPl)
                            .addComponent(jTextFieldCityOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxProtected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButtonCadre)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jTextFieldBldgNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonNonCadre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPostalCd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPostalCd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxRepresente)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAssist)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNonCadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNonCadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNonCadreActionPerformed

    private void jCheckBoxRepresenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRepresenteItemStateChanged
       
    }//GEN-LAST:event_jCheckBoxRepresenteItemStateChanged

    private void jCheckBoxAssistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAssistItemStateChanged
       
    }//GEN-LAST:event_jCheckBoxAssistItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DemRepreJPanel represantant = new DemRepreJPanel(getParentRoot());
            represantant.setParentRoot(getParentRoot());
            ActionListener actionlistener = new ActionListener() {

               @Override
               public void actionPerformed(ActionEvent e) {
                   System.out.println("Check box represantant");
               }
           };
            DialogDescriptor dd = new DialogDescriptor
                    (represantant, "Representant",true, actionlistener);
            Dialog resDls = DialogDisplayer.getDefault().createDialog(dd);
            resDls.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DemAssistJPanel represantant = new DemAssistJPanel(getParentRoot());
            represantant.setParentRoot(getParentRoot());
            ActionListener actionlistener = new ActionListener() {

               @Override
               public void actionPerformed(ActionEvent e) {
                   System.out.println("Check box assitant");
               }
           };
            DialogDescriptor dd = new DialogDescriptor
                    (represantant, "Representant",true, actionlistener);
            Dialog resDls = DialogDisplayer.getDefault().createDialog(dd);
            resDls.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCadre;
    private com.bi.right.customer.bo.GUIManager gUIManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxAssist;
    private javax.swing.JCheckBox jCheckBoxRepresente;
    private javax.swing.JComboBox jComboBoxNamePrefix1Code;
    private javax.swing.JComboBox jComboBoxProtected;
    private javax.swing.JFormattedTextField jFormattedTextFieldBirthDt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelBirthPl;
    private javax.swing.JLabel jLabelCitizenship;
    private javax.swing.JLabel jLabelJob;
    private javax.swing.JLabel jLabelNamePrefix1Code;
    private javax.swing.JLabel jLabelNm;
    private javax.swing.JLabel jLabelPhneNb;
    private javax.swing.JLabel jLabelPostalCd;
    private javax.swing.JLabel jLabelPrenomDemandeur;
    private javax.swing.JLabel jLabelProtect;
    private javax.swing.JRadioButton jRadioButtonCadre;
    private javax.swing.JRadioButton jRadioButtonNonCadre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldBldgNb;
    private javax.swing.JTextField jTextFieldCitizen;
    private javax.swing.JTextField jTextFieldCityOfBirth;
    private javax.swing.JTextField jTextFieldJob;
    private javax.swing.JTextField jTextFieldNm;
    private javax.swing.JTextField jTextFieldPhneNb;
    private javax.swing.JTextField jTextFieldPostalCd;
    private javax.swing.JTextField jTextFieldVille;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<Document> getUndoableDocuments() {
        ArrayList<Document> prj = new ArrayList<Document>();

        prj.add(jFormattedTextFieldBirthDt.getDocument());
        prj.add(jTextField1.getDocument());
        prj.add(jTextField2.getDocument());
        prj.add(jTextField3.getDocument());
        prj.add(jTextFieldBldgNb.getDocument());
        prj.add(jTextFieldCitizen.getDocument());
        prj.add(jTextFieldCityOfBirth.getDocument());
        prj.add(jTextFieldJob.getDocument());
        prj.add(jTextFieldNm.getDocument());
        prj.add(jTextFieldPhneNb.getDocument());
        prj.add(jTextFieldPostalCd.getDocument());
        prj.add(jTextFieldVille.getDocument());

        return prj;
    }

     @Override
    public boolean isNextPossible() {
        if (isEmpty(jFormattedTextFieldBirthDt,
                jTextFieldCitizen,jTextField1,
                jTextFieldVille,jTextFieldBldgNb,
                jTextFieldPostalCd,jTextFieldVille,
                jTextFieldNm,jTextField2)) {
            return false;
        }
        return true;
    }
    @Override
    public BindingGroup getBindingGroup() {
        return bindingGroup;
    }
    
     @Override
    public void initJComponents() {
        initComponents();
    }
}
