/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel;

import com.bi.right.customer.bo.Defendeur;
import com.bi.right.customer.bopanel.PersonneBoPanel;
import com.bi.right.customer.util.naf.R1441_9;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class SalarieDefendeurJPanel extends AbstractPanel {

    /**
     * Creates new form SalarieDefendeurJPanel
     */
    public SalarieDefendeurJPanel() {
	initComponents();
    }

    public SalarieDefendeurJPanel(Defendeur defndeur) {
	this.defendeur = defndeur;
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defendeur = new com.bi.right.customer.bo.Defendeur();
        jCheckBox1 = new javax.swing.JCheckBox();
        personneBoPanel1 = new PersonneBoPanel(getDefendeur().getPersonne(),"Salarié defendeur");
        adresseJPanel1 = new com.bi.right.customer.bopanel.AdresseJPanel(getDefendeur().getPersonne().getAddr(),getDefendeur().getPersonne().getTel(),getDefendeur().getPersonne().getFax());

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(SalarieDefendeurJPanel.class, "SalarieDefendeurJPanel.jCheckBox1.text")); // NOI18N
        jCheckBox1.setToolTipText(org.openide.util.NbBundle.getMessage(SalarieDefendeurJPanel.class, "SalarieDefendeurJPanel.jCheckBox1.toolTipText")); // NOI18N
        add(jCheckBox1, java.awt.BorderLayout.NORTH);
        add(personneBoPanel1, java.awt.BorderLayout.CENTER);
        add(adresseJPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.bopanel.AdresseJPanel adresseJPanel1;
    private com.bi.right.customer.bo.Defendeur defendeur;
    private javax.swing.JCheckBox jCheckBox1;
    private com.bi.right.customer.bopanel.PersonneBoPanel personneBoPanel1;
    // End of variables declaration//GEN-END:variables

    public Defendeur getDefendeur() {
	return defendeur;
    }

    public void setDefendeur(Defendeur defendeur) {
	this.defendeur = defendeur;
    }

    @Override
    public void initJComponents() {
	initComponents();
    }

    @Override
    public List<Document> getUndoableDocuments() {
	List<Document> res = new ArrayList<Document>();
	personneBoPanel1.fillTextFields(res);
	adresseJPanel1.fillTextFields(res);
	return res;
    }

    @Override
    public BindingGroup getBindingGroup() {
	return personneBoPanel1.getBindingGroup();
    }

    @Override
    public boolean isNextPossible() {
	if (this.jCheckBox1.isSelected()) {
	    getParentRoot().getConseil().setSection("Encadrement");
	} else {
	    if (getParentRoot().getDemandeur().getSocId() != null) {
		String nafApe = getParentRoot().getDemandeur().getSocId().getNafape();
		if (nafApe != null) {
		    String section = R1441_9.getInstance().calcSection(nafApe, false);
		    if (section != null) {
			getParentRoot().getConseil().setSection(section);
		    }
		}
	    } 
	}
	return personneBoPanel1.isEmpty(this);
    }
}
