/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel;

import com.bi.right.customer.bo.GUIManager;
import com.bi.right.customer.bopanel.SocieteBoPanel;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class SocieteDemandeurJPanel extends AbstractPanel {
    private Dialog rPanel;
    private Dialog aPanel;

    /**
     * Creates new form SocieteDemandeurJPanel
     */
    public SocieteDemandeurJPanel() {
	initComponents();
    }

    public SocieteDemandeurJPanel(GUIManager root) {
	super(root);
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        gUIManager1 = getParentRoot();
        jCheckBoxRepresente = new javax.swing.JCheckBox();
        jButtonReprente = new javax.swing.JButton();
        jCheckBoxAssiste = new javax.swing.JCheckBox();
        jButtonAssist = new javax.swing.JButton();
        societeBoPanel1 = new SocieteBoPanel(getParentRoot().getDemandeur().getSocId());
        adresseJPanel1 = new com.bi.right.customer.bopanel.AdresseJPanel(getParentRoot().getDemandeur().getSocId().getAddr(),getParentRoot().getDemandeur().getSocId().getRprsnt().getTel(),getParentRoot().getDemandeur().getSocId().getRprsnt().getFax());

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxRepresente, org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jCheckBoxRepresente.text")); // NOI18N
        jCheckBoxRepresente.setToolTipText(org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jCheckBoxRepresente.toolTipText")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${defendeur.represente}"), jCheckBoxRepresente, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBoxRepresente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRepresenteItemStateChanged(evt);
            }
        });
        jCheckBoxRepresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRepresenteActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonReprente, org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jButtonReprente.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxRepresente, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jButtonReprente, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonReprente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReprenteActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxAssiste, org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jCheckBoxAssiste.text")); // NOI18N
        jCheckBoxAssiste.setToolTipText(org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jCheckBoxAssiste.toolTipText")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUIManager1, org.jdesktop.beansbinding.ELProperty.create("${demandeur.assiste}"), jCheckBoxAssiste, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBoxAssiste.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAssisteItemStateChanged(evt);
            }
        });
        jCheckBoxAssiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAssisteActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAssist, org.openide.util.NbBundle.getMessage(SocieteDemandeurJPanel.class, "SocieteDemandeurJPanel.jButtonAssist.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jCheckBoxAssiste, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jButtonAssist, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonAssist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssistActionPerformed(evt);
            }
        });

        societeBoPanel1.setAbstractPanel(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(societeBoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxRepresente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReprente)
                        .addGap(48, 48, 48)
                        .addComponent(jCheckBoxAssiste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssist))
                    .addComponent(adresseJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReprente)
                    .addComponent(jCheckBoxRepresente)
                    .addComponent(jCheckBoxAssiste)
                    .addComponent(jButtonAssist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(societeBoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adresseJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRepresenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRepresenteItemStateChanged

    }//GEN-LAST:event_jCheckBoxRepresenteItemStateChanged

    private void jCheckBoxRepresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRepresenteActionPerformed

    }//GEN-LAST:event_jCheckBoxRepresenteActionPerformed

    private void jButtonReprenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReprenteActionPerformed
        if (rPanel == null)   
	rPanel = showDefenseurPopup(this.gUIManager1.getDemandeur().getRepresentant(),"Représenté par");
        else
	    rPanel.setVisible(true);
	
    }//GEN-LAST:event_jButtonReprenteActionPerformed

    private void jCheckBoxAssisteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAssisteItemStateChanged

    }//GEN-LAST:event_jCheckBoxAssisteItemStateChanged

    private void jCheckBoxAssisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAssisteActionPerformed

    }//GEN-LAST:event_jCheckBoxAssisteActionPerformed

    private void jButtonAssistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssistActionPerformed
       if (aPanel == null) {
	    aPanel =  showDefenseurPopup(this.gUIManager1.getDemandeur().getAssistant(),"Assisté par");
	}
       else {
	    aPanel.setVisible(true);
	}
       
    }//GEN-LAST:event_jButtonAssistActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.bopanel.AdresseJPanel adresseJPanel1;
    private com.bi.right.customer.bo.GUIManager gUIManager1;
    private javax.swing.JButton jButtonAssist;
    private javax.swing.JButton jButtonReprente;
    private javax.swing.JCheckBox jCheckBoxAssiste;
    private javax.swing.JCheckBox jCheckBoxRepresente;
    private com.bi.right.customer.bopanel.SocieteBoPanel societeBoPanel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initJComponents() {
	initComponents();
    }

    @Override
    public List<Document> getUndoableDocuments() {
	List<Document> res = new ArrayList<Document>();
	societeBoPanel1.fillTextFields(res);
	return res;
    }

    @Override
    public BindingGroup getBindingGroup() {
	return this.bindingGroup;
    }

    @Override
    public boolean isNextPossible() {
	return societeBoPanel1.isEmpty(this);
    }
}
