package com.bi.right.state;

public enum Item {

	CPH, DEMADEUR, 
	DEFENDEUR,
	DEMANDES, 
	DISCUSSIONS, 
	PIECES, 
	ADDR, 
	EXPOSE_LITIGE, 
	SECTION, 
	REDRESSEMENT_CREDITOR,
	REDRESSEMENT_ADMINISTRATEUR, 
	CONTRAT_START_BEFORE_ENDDATE,
	CONTRAT_START, 
	CONTRAT_END,
	DEFENDEUR_SALARIE, 
	DEFENDEUR_SOCIETE, 
	DEMANDEUR_SALARIE, 
	DEMANDEUR_SOCIETE, 
	DEMANDE_AMOUNT,
	DEFENDEUR_DEMANDEUR,
	LIQUIDATION_ENDROIT,
	REDRESSEMENT_ENDROIT,
	LIQUIDATION,
	LIQUIDATION_DATE,
	AFFAIRE;
}
