/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel.sub;

import com.bi.right.customer.bo.Defenseur;
import com.bi.right.customer.bo.GUIManager;
import com.bi.right.customer.panel.AbstractPanel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class DemRepreJPanel extends AbstractPanel {

    

    public List<Document> getUndoableDocuments() {
        return defenseurJPanel1.getUndoableDocuments();
    }

    public BindingGroup getBindingGroup() {
        return defenseurJPanel1.getBindingGroup();
    }

    /**
     * Creates new form DemRepreJPanel
     */
    public DemRepreJPanel(GUIManager p) {
	super(p);
	if (getParentRoot().getDemandeur().getRepresentant() == null){
          getParentRoot().getDemandeur().setRepresentant(new Defenseur());
	}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUIManager1 = getParentRoot();
        defenseurJPanel1 = new DefenseurJPanel(getParentRoot().getDemandeur().getRepresentant());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(defenseurJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(defenseurJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.panel.sub.DefenseurJPanel defenseurJPanel1;
    private com.bi.right.customer.bo.GUIManager gUIManager1;
    // End of variables declaration//GEN-END:variables

 @Override
    public void initJComponents() {
        initComponents();
    }
 
  @Override
    public boolean isNextPossible() {
        return getParentRoot().getDemandeur().isRepresente();
    }
}
