/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel.sub;

import com.bi.calendar.dlg.DateChooser;
import com.bi.right.customer.bo.Liquidation;
import com.bi.right.customer.panel.AbstractPanel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;
import org.openide.windows.WindowManager;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class LiquidationJPanel extends AbstractPanel {

    /**
     * Creates new form LiquidationJPanel
     */
    public LiquidationJPanel() {
	initComponents();
    }

    public LiquidationJPanel(Liquidation pliquidation) {
	this.liquidation = pliquidation;
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        liquidation = getLiquidation();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldLiquidationDT = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        personneBoPanel1 = new com.bi.right.customer.bopanel.PersonneBoPanel(getLiquidation().getLiquidateur(),"Mandataire liquidateur");
        adresseJPanel1 = new com.bi.right.customer.bopanel.AdresseJPanel(getLiquidation().getLiquidateur().getAddr(),getLiquidation().getLiquidateur().getTel(),getLiquidation().getLiquidateur().getFax());

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerSize(15);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setDoubleBuffered(true);
        jSplitPane1.setOneTouchExpandable(true);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(LiquidationJPanel.class, "LiquidationJPanel.jLabel6.text")); // NOI18N

        jFormattedTextFieldLiquidationDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldLiquidationDT.setToolTipText(org.openide.util.NbBundle.getMessage(LiquidationJPanel.class, "LiquidationJPanel.jFormattedTextFieldLiquidationDT.toolTipText")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, liquidation, org.jdesktop.beansbinding.ELProperty.create("${startdt}"), jFormattedTextFieldLiquidationDT, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldLiquidationDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldLiquidationDTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(jFormattedTextFieldLiquidationDT, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jFormattedTextFieldLiquidationDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerSize(15);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setAutoscrolls(true);
        jSplitPane2.setContinuousLayout(true);
        jSplitPane2.setOneTouchExpandable(true);
        jSplitPane2.setLeftComponent(personneBoPanel1);
        jSplitPane2.setRightComponent(adresseJPanel1);

        jPanel2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldLiquidationDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldLiquidationDTMouseClicked
        if (evt.getClickCount() == 2) {
	    DateChooser dc = new DateChooser(WindowManager.getDefault().getMainWindow(), jFormattedTextFieldLiquidationDT);
	    dc.setLocationRelativeTo(jFormattedTextFieldLiquidationDT);
	    dc.setLocation(evt.getPoint());

	    dc.setVisible(true);
	}
	
    }//GEN-LAST:event_jFormattedTextFieldLiquidationDTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.bopanel.AdresseJPanel adresseJPanel1;
    private javax.swing.JFormattedTextField jFormattedTextFieldLiquidationDT;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private com.bi.right.customer.bo.Liquidation liquidation;
    private com.bi.right.customer.bopanel.PersonneBoPanel personneBoPanel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    @Override
    public List<Document> getUndoableDocuments() {
	List<Document> p = new ArrayList<Document>();
	personneBoPanel1.fillTextFields(p);
	adresseJPanel1.fillTextFields(p);
	return p;
    }

    @Override
    public BindingGroup getBindingGroup() {
	return bindingGroup;
    }

    @Override
    public void initJComponents() {
	initComponents();
    }

    @Override
    public boolean isNextPossible() {
	/*if (isEmpty(jTextFieldNm1,jTextFieldBldgNb1,jTextField6,jTextFieldPostalCd1,jTextFieldVille))
	 {
	 return false;
	 }*/
	return true;

    }

    public Liquidation getLiquidation() {
	return liquidation;
    }

    public void setLiquidation(Liquidation liquidation) {
	this.liquidation = liquidation;
    }
    
    
}
