/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.panel.sub;

import com.bi.right.customer.bo.Personne;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class RepresentantLegalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RepresentantLegalJPanel
     */
    public RepresentantLegalJPanel() {
	initComponents();
    }

    public RepresentantLegalJPanel(Personne personne) {
	this.personne = personne;
	initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personne = getPersonne();
        personneBoPanel1 = new com.bi.right.customer.bopanel.PersonneBoPanel(getPersonne(),"Représentant légal");

        setLayout(new java.awt.BorderLayout());
        add(personneBoPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bi.right.customer.bo.Personne personne;
    private com.bi.right.customer.bopanel.PersonneBoPanel personneBoPanel1;
    // End of variables declaration//GEN-END:variables

    public Personne getPersonne() {
	return personne;
    }

    public void setPersonne(Personne personne) {
	this.personne = personne;
    }

}
