/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer;

import com.bi.calendar.dlg.DateChooser;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.Dictionary;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFormattedTextField;
import javax.swing.plaf.LabelUI;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//com.bi.right.customer//EditeurDERegles//EN",
autostore = true)
@TopComponent.Description(
    preferredID = "EditeurDEReglesTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "com.bi.right.customer.EditeurDEReglesTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_EditeurDEReglesAction",
preferredID = "EditeurDEReglesTopComponent")
@Messages({
    "CTL_EditeurDEReglesAction=Règles de licenciement",
    "CTL_EditeurDEReglesTopComponent=Fenêtre de règle de licenciement",
    "HINT_EditeurDEReglesTopComponent=Ce ci est la fenêtre d'édition de règle de licenciement"
})
public final class EditeurDEReglesTopComponent extends TopComponent {

    public EditeurDEReglesTopComponent() {
	initComponents();
	setName(Bundle.CTL_EditeurDEReglesTopComponent());
	setToolTipText(Bundle.HINT_EditeurDEReglesTopComponent());
	
	   
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rules1 = new com.bi.right.customer.bo.Rules();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabelConnnasanceFaits = new javax.swing.JLabel();
        jFormattedTextFieldNmobre = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelConnnasanceFaits1 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre1 = new javax.swing.JFormattedTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabelConnnasanceFaits2 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre2 = new javax.swing.JFormattedTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabelConnnasanceFaits3 = new javax.swing.JLabel();
        jFormattedTextFieldPreavisdur = new javax.swing.JFormattedTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre4 = new javax.swing.JFormattedTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre5 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre6 = new javax.swing.JFormattedTextField();
        jLabelConnnasanceFaits4 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre7 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNmobre8 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre9 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre10 = new javax.swing.JFormattedTextField();
        jLabelConnnasanceFaits5 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre11 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextFieldNmobre12 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel4.text")); // NOI18N

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField1.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField1.text")); // NOI18N
        jFormattedTextField1.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField1.toolTipText")); // NOI18N
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField2.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField2.text")); // NOI18N
        jFormattedTextField2.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField2.toolTipText")); // NOI18N
        jFormattedTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField2MouseClicked(evt);
            }
        });

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField3.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField3.text")); // NOI18N
        jFormattedTextField3.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField3.toolTipText")); // NOI18N
        jFormattedTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField3MouseClicked(evt);
            }
        });

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField4.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField4.text")); // NOI18N
        jFormattedTextField4.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField4.toolTipText")); // NOI18N
        jFormattedTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField4MouseClicked(evt);
            }
        });

        jLabelConnnasanceFaits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits.text")); // NOI18N

        jFormattedTextFieldNmobre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre.text_1")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mois", "Jour(s)", "Année(s)", " " }));

        jLabelConnnasanceFaits1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits1, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits1.text")); // NOI18N

        jFormattedTextFieldNmobre1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre1.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre1.text")); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jour(s)", "Mois", "Année(s)", " " }));

        jLabelConnnasanceFaits2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits2, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits2.text")); // NOI18N

        jFormattedTextFieldNmobre2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre2.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre2.text")); // NOI18N

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jour(s)", "Mois", "Année(s)", " " }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel5.text")); // NOI18N

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField5.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField5.text")); // NOI18N
        jFormattedTextField5.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextField5.toolTipText")); // NOI18N
        jFormattedTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField5MouseClicked(evt);
            }
        });

        jLabelConnnasanceFaits3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits3, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits3.text")); // NOI18N

        jFormattedTextFieldPreavisdur.setBackground(new java.awt.Color(102, 255, 204));
        jFormattedTextFieldPreavisdur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldPreavisdur.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldPreavisdur.text")); // NOI18N

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mois", "Jour(s)", "Année(s)", " " }));

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jCheckBox1.text")); // NOI18N
        jCheckBox1.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jCheckBox1.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox2, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jCheckBox2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox3, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jCheckBox3.text")); // NOI18N
        jCheckBox3.setToolTipText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jCheckBox3.toolTipText")); // NOI18N

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()+3f));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jButton1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jButton2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel9.text")); // NOI18N

        jFormattedTextFieldNmobre4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre4.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre4.text")); // NOI18N

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mois", "Jour(s)", "Année(s)", " " }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel10.text")); // NOI18N

        jFormattedTextFieldNmobre5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre5.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel11.text")); // NOI18N

        jFormattedTextFieldNmobre6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre6.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre6.text")); // NOI18N

        jLabelConnnasanceFaits4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits4, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits4.text")); // NOI18N

        jFormattedTextFieldNmobre7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre7.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre7.text")); // NOI18N

        jFormattedTextFieldNmobre8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre8.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel12.text")); // NOI18N

        jFormattedTextFieldNmobre9.setBackground(jFormattedTextFieldPreavisdur.getBackground());
        jFormattedTextFieldNmobre9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre9.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel13.text")); // NOI18N

        jFormattedTextFieldNmobre10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre10.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre10.text")); // NOI18N

        jLabelConnnasanceFaits5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bi/right/customer/fleche32x32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelConnnasanceFaits5, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabelConnnasanceFaits5.text")); // NOI18N

        jFormattedTextFieldNmobre11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre11.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre11.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jLabel14.text")); // NOI18N

        jFormattedTextFieldNmobre12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNmobre12.setText(org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jFormattedTextFieldNmobre12.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(EditeurDEReglesTopComponent.class, "EditeurDEReglesTopComponent.jButton3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldNmobre10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jFormattedTextFieldNmobre6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jFormattedTextFieldNmobre4)
                                                .addComponent(jFormattedTextFieldNmobre5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11))))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldNmobre9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabelConnnasanceFaits5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldNmobre11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldNmobre12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelConnnasanceFaits4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldNmobre7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldNmobre8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jCheckBox2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jCheckBox1)
                                                        .addGap(48, 48, 48)
                                                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelConnnasanceFaits3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldPreavisdur, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelConnnasanceFaits)
                                            .addGap(18, 18, 18)
                                            .addComponent(jFormattedTextFieldNmobre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelConnnasanceFaits1)
                                                .addComponent(jLabelConnnasanceFaits2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldNmobre2)
                                                .addComponent(jFormattedTextFieldNmobre1)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelConnnasanceFaits)
                                    .addComponent(jFormattedTextFieldNmobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jCheckBox2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelConnnasanceFaits1)
                                    .addComponent(jFormattedTextFieldNmobre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelConnnasanceFaits2)
                            .addComponent(jFormattedTextFieldNmobre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox1)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConnnasanceFaits3)
                    .addComponent(jFormattedTextFieldPreavisdur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldNmobre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jFormattedTextFieldNmobre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jFormattedTextFieldNmobre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelConnnasanceFaits4)
                                    .addComponent(jFormattedTextFieldNmobre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldNmobre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jFormattedTextFieldNmobre9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelConnnasanceFaits5)
                                    .addComponent(jFormattedTextFieldNmobre11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldNmobre12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))))
                    .addComponent(jFormattedTextFieldNmobre10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
        
	if (evt.getClickCount() == 2) {
	    openDateChooser(evt,this.jFormattedTextField1);
	}
    }

    private void openDateChooser(MouseEvent evt,JFormattedTextField jFormattedText) {
	
	DateChooser dc = new DateChooser(WindowManager.getDefault().getMainWindow(), jFormattedText);
	dc.setLocationRelativeTo(jFormattedText);
	dc.setLocation(evt.getPoint());
       // dc.setUseHour(true);
	dc.setVisible(true);
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jFormattedTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField2MouseClicked
        if (evt.getClickCount() == 2) {
	    openDateChooser(evt,jFormattedTextField2);
	}
    }//GEN-LAST:event_jFormattedTextField2MouseClicked

    private void jFormattedTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField3MouseClicked
        if (evt.getClickCount() == 2) {
	    openDateChooser(evt,jFormattedTextField3);
	}
    }//GEN-LAST:event_jFormattedTextField3MouseClicked

    private void jFormattedTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField4MouseClicked
       if (evt.getClickCount() == 2) {
	    openDateChooser(evt,jFormattedTextField4);
	}
    }//GEN-LAST:event_jFormattedTextField4MouseClicked

    private void jFormattedTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField5MouseClicked
        if (evt.getClickCount() == 2) {
	    openDateChooser(evt,jFormattedTextField5);
	}
    }//GEN-LAST:event_jFormattedTextField5MouseClicked

    class DateDictionnary extends Dictionary {

	private Map<Integer,Date> t = new HashMap<Integer,Date>();
	    void fill(Date start){
		t.put(0, start);
		Calendar c = Calendar.getInstance();
		c.setTime(start);
		for (int i = 1; i < 25; i++) {
		    c.add(Calendar.MONTH, i);
		    t.put(i, c.getTime());
		}
	    }
	    @Override
	    public int size() {
		return t.size();
	    }

	    @Override
	    public boolean isEmpty() {
		return t.isEmpty();
	    }

	    @Override
	    public Enumeration keys() {
		return Collections.enumeration(t.keySet()) ;
	    }

	    @Override
	    public Enumeration elements() {
		return Collections.enumeration(t.values()) ;
	    }

	    @Override
	    public Object get(Object key) {
		return t.get(key);
	    }

	    @Override
	    public Object put(Object key, Object value) {
		t.put((Integer)key, (Date)value);
		return value;
	    }

	    @Override
	    public Object remove(Object key) {
		return t.remove(key);
	    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre1;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre10;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre11;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre12;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre2;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre4;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre5;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre6;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre7;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre8;
    private javax.swing.JFormattedTextField jFormattedTextFieldNmobre9;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreavisdur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConnnasanceFaits;
    private javax.swing.JLabel jLabelConnnasanceFaits1;
    private javax.swing.JLabel jLabelConnnasanceFaits2;
    private javax.swing.JLabel jLabelConnnasanceFaits3;
    private javax.swing.JLabel jLabelConnnasanceFaits4;
    private javax.swing.JLabel jLabelConnnasanceFaits5;
    private com.bi.right.customer.bo.Rules rules1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
	// TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
	// TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
	// better to version settings since initial version as advocated at
	// http://wiki.apidesign.org/wiki/PropertyFiles
	p.setProperty("version", "1.0");
	// TODO store your settings
    }

    void readProperties(java.util.Properties p) {
	String version = p.getProperty("version");
	// TODO read your settings according to their version
    }
}
