/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bi.right.customer.bopanel;

import com.bi.right.customer.bo.Personne;
import com.bi.right.customer.panel.AbstractPanel;
import com.bi.right.customer.panel.SalarieDefendeurJPanel;
import com.bi.right.customer.panel.sub.PComboModel;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.text.Document;
import org.jdesktop.beansbinding.BindingGroup;

/**
 *
 * @author rafaralahitsimba tiaray
 */
public class PersonneBoPanel extends AbstractBoPanel {

    
  
    /**
     * Creates new form PersonneBoPanel
     */
    public PersonneBoPanel() {
	initComponents();
	
    }

    public PersonneBoPanel(Personne personne,String panelName) {
	this.personne = personne;
	initComponents();
	jLabel1.setText(panelName);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        personne = personne;
        jLabel1 = new javax.swing.JLabel();
        jLabelNamePrefix1Code = new javax.swing.JLabel();
        jComboBoxNamePrefix1Code = new javax.swing.JComboBox();
        jLabelNm = new javax.swing.JLabel();
        jTextFieldNm = new javax.swing.JTextField();
        jLabelPrenomDemandeur = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PersonneBoPanel.class, "PersonneBoPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNamePrefix1Code, org.openide.util.NbBundle.getMessage(PersonneBoPanel.class, "PersonneBoPanel.jLabelNamePrefix1Code.text")); // NOI18N

        jComboBoxNamePrefix1Code.setModel(new PComboModel());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, personne, org.jdesktop.beansbinding.ELProperty.create("${civilite}"), jComboBoxNamePrefix1Code, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelNm, org.openide.util.NbBundle.getMessage(PersonneBoPanel.class, "PersonneBoPanel.jLabelNm.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, personne, org.jdesktop.beansbinding.ELProperty.create("${nm}"), jTextFieldNm, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelPrenomDemandeur, org.openide.util.NbBundle.getMessage(PersonneBoPanel.class, "PersonneBoPanel.jLabelPrenomDemandeur.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, personne, org.jdesktop.beansbinding.ELProperty.create("${pnm}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrenomDemandeur)
                            .addComponent(jLabelNm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNamePrefix1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxNamePrefix1Code, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamePrefix1Code)
                    .addComponent(jComboBoxNamePrefix1Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNm)
                    .addComponent(jTextFieldNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomDemandeur)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxNamePrefix1Code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNamePrefix1Code;
    private javax.swing.JLabel jLabelNm;
    private javax.swing.JLabel jLabelPrenomDemandeur;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldNm;
    private com.bi.right.customer.bo.Personne personne;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

   

    
    public void fillTextFields(List<Document> l) {
	
	l.add(jTextField1.getDocument());
	l.add(jTextFieldNm.getDocument());
    }

    public boolean isEmpty(SalarieDefendeurJPanel aThis) {
	return aThis.isEmpty(jTextField1,jTextFieldNm);
    }

    public BindingGroup getBindingGroup() {
	return bindingGroup;
    }
}
